@baseUrl=http://localhost:8080

###
GET {{baseUrl}}

### 
POST {{baseUrl}}/expense
Content-Type: application/json

{
  "amount": 800
}

### 
GET {{baseUrl}}/expense

### 
GET {{baseUrl}}/character

###

POST {{baseUrl}}/character/login

###
GET {{baseUrl}}/category

###
POST {{baseUrl}}/category
Content-Type: application/json

{
  "name": "life"
}

### 
POST {{baseUrl}}/slack/notify
Content-Type: application/json

{
  "message": "slack message from goalngggggggggggg"
}


### 
POST {{baseUrl}}/user/signup
Content-Type: application/json

{
  "name": "name1",
  "email": "test@test.com",
  "password": "password"
}